-- Adds order history for signed-in buyers, seller reviews, and
-- self-service account deletion.
--
-- Run this once in the Supabase SQL Editor for your project (after
-- schema.sql, migration_fix_profile_rls.sql, migration_add_orders.sql,
-- migration_products_and_signup.sql, migration_add_cart.sql and
-- migration_add_product_images.sql).

alter table public.orders add column if not exists user_id uuid references auth.users(id) on delete set null;

drop policy if exists "Users can view own orders" on public.orders;
create policy "Users can view own orders" on public.orders for select using (auth.uid() = user_id);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references auth.users(id) on delete cascade,
  reviewer_id uuid not null references auth.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  unique (seller_id, reviewer_id)
);

alter table public.reviews enable row level security;

drop policy if exists "Public can view reviews" on public.reviews;
create policy "Public can view reviews" on public.reviews for select using (true);

drop policy if exists "Users can leave reviews" on public.reviews;
create policy "Users can leave reviews" on public.reviews for insert with check (auth.uid() = reviewer_id and auth.uid() <> seller_id);

drop policy if exists "Users can update own reviews" on public.reviews;
create policy "Users can update own reviews" on public.reviews for update using (auth.uid() = reviewer_id);

drop policy if exists "Users can delete own reviews" on public.reviews;
create policy "Users can delete own reviews" on public.reviews for delete using (auth.uid() = reviewer_id);

-- The only legitimate way a client (non-admin) key can delete a user's own
-- auth.users row. Everything else (profiles, listings, listing_images,
-- favorites, cart_items, reviews) already cascades via existing foreign
-- keys; orders.user_id is "on delete set null" so financial records
-- survive account deletion, just detached from the deleted account.
create or replace function public.delete_own_account()
returns void language plpgsql security definer set search_path = public
as $$
begin
  delete from auth.users where id = auth.uid();
end;
$$;
