-- Adds server-side cart storage so a signed-in user's cart follows them
-- across devices/browsers instead of only living in localStorage.
--
-- Run this once in the Supabase SQL Editor for your project (after
-- schema.sql, migration_fix_profile_rls.sql, migration_add_orders.sql and
-- migration_products_and_signup.sql).

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null,
  created_at timestamptz not null default now()
);

alter table public.cart_items enable row level security;

drop policy if exists "Users can manage own cart" on public.cart_items;
create policy "Users can manage own cart" on public.cart_items for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
