-- Adds real order storage so checkout actually submits order requests.
-- Run this once in the Supabase SQL Editor for your project (after
-- migration_fix_profile_rls.sql).

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  buyer_name text not null,
  buyer_email text not null,
  buyer_phone text,
  buyer_address text not null,
  notes text,
  status text not null default 'pending' check (status in ('pending', 'paid', 'shipped', 'completed', 'cancelled')),
  total numeric(10, 2) not null check (total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  price numeric(10, 2) not null,
  quantity integer not null default 1
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Anyone (including anonymous visitors) can submit an order request.
create policy "Anyone can create an order" on public.orders for insert with check (true);
create policy "Anyone can create order items" on public.order_items for insert with check (true);

-- Only admins (owner/manager/warehouse/fulfillment roles) can see or update orders.
create policy "Admins can view all orders" on public.orders for select using (public.is_admin());
create policy "Admins can update orders" on public.orders for update using (public.is_admin());
create policy "Admins can view order items" on public.order_items for select using (public.is_admin());
