create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  phone text,
  city text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique
);

create table public.listings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category_id bigint references public.categories(id),
  title text not null,
  description text,
  price numeric(10, 2) not null check (price >= 0),
  condition text not null default 'good' check (condition in ('very_good', 'good', 'defect')),
  oem_number text,
  brand text,
  model text,
  production_year integer,
  engine text,
  location text,
  status text not null default 'pending' check (status in ('pending', 'active', 'reserved', 'sold', 'removed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.listings add column if not exists category text;

create table public.listing_images (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  storage_path text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  listing_id bigint not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, listing_id)
);

create table public.reports (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  reporter_id uuid references auth.users(id) on delete set null,
  reason text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.listings enable row level security;
alter table public.listing_images enable row level security;
alter table public.favorites enable row level security;
alter table public.reports enable row level security;

create policy "Public can view active listings" on public.listings for select using (status = 'active' or auth.uid() = user_id);
create policy "Users can create listings" on public.listings for insert with check (auth.uid() = user_id);
create policy "Users can update their listings" on public.listings for update using (auth.uid() = user_id);
create policy "Users can delete their listings" on public.listings for delete using (auth.uid() = user_id);
create policy "Public can view categories" on public.categories for select using (true);
create policy "Users can manage own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "Public can view seller profiles" on public.profiles for select using (true);
create policy "Public can view listing images" on public.listing_images for select using (true);
create policy "Owners can manage listing images" on public.listing_images for all using (exists (select 1 from public.listings where id = listing_id and user_id = auth.uid()));
create policy "Users can manage own favorites" on public.favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can submit reports" on public.reports for insert with check (auth.uid() = reporter_id);

insert into public.categories (name, slug) values
  ('Dzinējs', 'dzinējs'), ('Virsbūve', 'virsbūve'), ('Salons', 'salons'),
  ('Balstiekārta', 'balstiekārta'), ('Elektrība', 'elektrība'), ('Riteņi un diski', 'ritenji-un-diski')
on conflict (slug) do nothing;
